name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: install pytest
        run: pip3 install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Branche
        run: echo"Nom branche : $ { { github . r e f } } "
      - name: Afficher l'OS de la VM
        run: echo "Système d'exploitation de la VM : ${{ runner.os }}"
